- hosts: aws_ec2
  become: true
  gather_facts: true

  roles:
  - role: containerd
  - role: common
  - role: kubernetes

- hosts: group_Name_master
  become: true
  gather_facts: true

  roles:
  - role: master
  - role: cni

  tasks:
  - name: Install required packages
    apt:
      name:
      - curl
      - software-properties-common
      state: present
      update_cache: yes

  - name: Download Helm installation script
    get_url:
      url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      dest: ./get_helm.sh
      mode: 'u+x' # Make it executable

  - name: Run the Helm installation script with superuser privileges
    command: ./get_helm.sh
    args:
      executable: /bin/bash

  - name: Clean up installation script
    file:
      path: ./get_helm.sh
      state: absent

  - name: Verify Helm installation
    command: helm version
    register: helm_version

  - debug:
      var: helm_version.stdout

  - name: Add the stable Helm repository
    command: helm repo add stable https://charts.helm.sh/stable

  - name: Update Helm repositories
    command: helm repo update

- hosts: group_Name_worker
  become: true
  gather_facts: true

  roles:
  - role: worker

- name: Deploy Helm Chart on Master Node
  hosts: roup_Name_master
  become: true
  tasks:
  - name: Clone the repository
    git:
      repo: 'https://github.com/Mahmoudshookry/DevOps-Project.git'
      dest: ~/DevOps-Project
      version: master # Specify the branch if needed
      force: yes # Optional: force overwrite if the directory already exists

  - name: Upgrade Helm release
    command: helm upgrade my-release ./helm-chart --values ./helm-chart/values.yaml --namespace testing-namespace --create-namespace
    args:
      chdir: ~/DevOps-Project/helm-chart
